package CotesApp;


/**
* CotesApp/ICotesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotes.idl
* Friday, October 18, 2019 3:21:24 PM BOT
*/

public interface ICotesOperations 
{
  int pendiente (int pendientes);
  int pago (int pagar);
  void shutdown ();
} // interface ICotesOperations
