package CotesApp;


/**
* CotesApp/ICotes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotes.idl
* Friday, October 18, 2019 3:21:24 PM BOT
*/

public interface ICotes extends ICotesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICotes
