package CotesApp;

/**
* CotesApp/ICotesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotes.idl
* Friday, October 18, 2019 3:21:24 PM BOT
*/

public final class ICotesHolder implements org.omg.CORBA.portable.Streamable
{
  public CotesApp.ICotes value = null;

  public ICotesHolder ()
  {
  }

  public ICotesHolder (CotesApp.ICotes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CotesApp.ICotesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CotesApp.ICotesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CotesApp.ICotesHelper.type ();
  }

}
